version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          dependency_type: "direct"
    automerged_updates:
      - match:
          update_type: "security:patch"
